version: '3.8'

services:
  ddd-db-postgres:
    container_name: ddd-db-postgres
    networks:
      - backend
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./container-data/postgres:/data/postgres
      - ./sql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.postgres.env

networks:
  backend:
    name: java-dbs-network
